Check that config.nb_hits_max is set before referencing
hopefully this fixes the nice error I'm seeing:

AttributeError: 'ConfigLoader' object has no attribute 'nb_hits_max'